version: '3.3'

services:
  event-store:
    image: postgres:10.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events
    volumes:
      - ./test-initialise-scripts:/docker-entrypoint-initdb.d

  flyway:
    image: platform-deployer-verify-data-db-migrations:latest-tests
    env_file:
      - test.env
    depends_on:
      - event-store

  psql:
    image: postgres:10.6
    command: psql
    env_file:
      - test.env
    depends_on:
      - event-store
